#!/bin/bash

target_dir_input=${1:-~/usr/}
target_dir=${target_dir_input/~/$HOME/}
mkdir -p ${target_dir}/include
mkdir -p ${target_dir}/bin
install -t ${target_dir}/include include/*.h include/*.hxx  include/*.hcc include/*.inc
install -t ${target_dir}/bin shell/* 

#DCSH_PATH_EXIST=`sed -n ":DCSH_PATH.*${target_dir}:p" ~/.bashrc`
DCSH_PATH_EXIST=`grep "DCSH_PATH.*${target_dir}" ~/.bashrc`
if [ -z "`grep 'DCSH_PATH.*${target_dir}/include' ~/.bashrc`" ]; then
    echo "export DCSH_PATH=$target_dir/include" >> ~/.bashrc 
fi
if [ -z "`grep 'PATH.*${target_dir}/bin' ~/.bashrc`" ]; then
    echo "export PATH=\$PATH:$target_dir/bin" >> ~/.bashrc 
fi
if [ -z "`grep 'alias rm=' ~/.bashrc`" ]; then
    echo "alias rm=$target_dir/bin/rm" >> ~/.bashrc 
    echo "alias unrm=$target_dir/bin/rm -u" >> ~/.bashrc 
fi
