ext_cflags:=-std=c++11
ext_inc:= ./
SOURCEFILE:= main.cpp \
	tree/pre_order_binary_tree.cpp \
	tree/post_order_binary_tree.cpp \
	tree/in_order_binary_tree.cpp \
	tree/is_balanced.cpp \
	tree/arrary_to_binary_tree.cpp \
	tree/arrary_to_binary_tree.cpp \
	tree/is_same_tree.cpp \
	\
	sort/kway_merge.cpp \
	sort/twosums.cpp \
	\
	combination/climbing_stairs.cpp \
	\
    binary_search/kth_element.cpp \
	binary_search/median_two_sort_array.cpp \
	binary_search/power.cpp \
	\
	dp/pascal_triangle.cpp \
	dp/longest_valid_parentheses.cpp \
	dp/permutation_sequence.cpp \
	\
	linkedlist/add_two_numbers.cpp \
	\
	graph/islands.cpp \
	graph/clone.cpp \



EXECUTABLE:=main
include ../include/makefile.inc
