ext_cflags:=-std=c++11
ext_inc:= ./
SOURCEFILE:= main.cpp \
	tree/pre_order_binary_tree.cpp \
	tree/post_order_binary_tree.cpp \
	tree/in_order_binary_tree.cpp \
	tree/is_balanced.cpp \
	\
	sort/kway_merge.cpp \
	\
	combination/climbing_stairs.cpp \
	\
        binary_search/kth_element.cpp \



EXECUTABLE:=main
include ../include/makefile.inc
